backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "games"
    label: "Games"
    folder: "games"
    create: true
    slug: "{{slug}}"

    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

      - {label: "Download URL", name: "game_url", widget: "string"}

      - {label: "Thumbnail", name: "thumbnail", widget: "image"}

      - {label: "Version", name: "version", widget: "string", required: false}
      - {label: "Size", name: "size", widget: "string", required: false}
      - {label: "Android", name: "android", widget: "string", required: false}
      - {label: "Developer", name: "developer", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string", required: false}

      - {label: "Screenshot 1", name: "screenshot1", widget: "image", required: false}
      - {label: "Screenshot 2", name: "screenshot2", widget: "image", required: false}
      - {label: "Screenshot 3", name: "screenshot3", widget: "image", required: false}
      - {label: "Screenshot 4", name: "screenshot4", widget: "image", required: false}
      - {label: "Screenshot 5", name: "screenshot5", widget: "image", required: false}

      - label: "MOD Features"
        name: "features"
        widget: "list"
        required: false
