name: Build Games JSON

on:
  push:
    paths:
      - "games/**"
      - "build-games.js"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node build-games.js

      - name: Commit updated index.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add games/games/index.json
          git diff --cached --quiet || git commit -m "Auto update index.json"
          git push
